import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
const b = await chromium.launch({ args: ['--lang=fr-FR'] });
const ctx = await b.newContext({ viewport: { width: 1280, height: 900 }, deviceScaleFactor: 2, locale: 'fr-FR', timezoneId: 'Europe/Paris' });
const fs = await import('fs');
const fcss = fs.readFileSync('brag-output/work/calc/fonts-inject.css','utf8');
await ctx.route(/fonts\.googleapis\.com|api\.fontshare\.com/, r => r.fulfill({ contentType:'text/css', body: fcss }));
await ctx.route(/googletagmanager|news\.google/, r => r.abort());
const p = await ctx.newPage();
await p.goto('http://localhost:8765/ms-strategy-calculateur.html', { waitUntil: 'networkidle' }).catch(()=>{});
await p.waitForTimeout(2500);
await p.addStyleTag({ content: '#cookie-banner,.cookie,[class*=cookie],[id*=cookie],nav,.nav,header.site-header{display:none!important}' });
const dir = 'brag-output/work/calc/';
await p.locator('.hero').screenshot({ path: dir+'hero.png' });
await p.locator('#taximeter').screenshot({ path: dir+'taxi-0.png' });
await p.fill('#input-conso','350'); await p.fill('#input-price','118'); await p.fill('#input-kva','36');
await p.fill('#input-renewal-date','2024-01-15');
await p.selectOption('#input-engaged','non'); await p.selectOption('#input-sector','restauration');
await p.locator('#input-months').fill('12').catch(()=>{});
await p.locator('#input-months').dispatchEvent('input');
await p.waitForTimeout(4000);
await p.evaluate(()=>{const d=document.querySelector('#input-renewal-date'); d.type='text'; d.value='15/01/2024';});
await p.locator('.inputs-section').screenshot({ path: dir+'inputs.png' });
await p.locator('#taximeter').screenshot({ path: dir+'taxi-1.png' });
await p.locator('.results-grid').screenshot({ path: dir+'results.png' });
await p.locator('.chart-section').screenshot({ path: dir+'chart.png' });
await p.locator('#verdict-box').screenshot({ path: dir+'verdict.png' }).catch(e=>console.log('verdict',e.message));
await b.close();
